[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='4d046c0be428830a6abd1d75538ddbe5e9d4477e5bd64da79df264951e11b8fd'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
